name: Automatically tag when version is upgraded

on:
  push:
    branches:
      - master

jobs:
  tag-new-version:
    name: Create tag for new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: salsify/action-detect-and-tag-new-version@v2
        id: create_new_version_tag
